name: CI
on:
  push:
  workflow_dispatch:

jobs:
  mac-aarch:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - name: DoSomething
      run: |
        uname -a
        arch

  mac-intel:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: DoSomething
      run: |
        uname -a
        arch
